name: SausageSMP.main
version: ${project.version}
main: sausagesmp.corruptsausage.sausagesmp.main.SausageSMP.Main
api-version: 1.16
authors: [ CorruptSausage ]
description: Base
## All commands:
commands:
  gms:
    description: Changes gamemode to survival
    usage: /<command>
  gmc:
    description: Changes gamemode to creative
    usage: /<command>
  day:
    description: Changes to daytime
    usage: /<command>
  night:
    description: Changes to nighttime
    usage: /<command>
  vanish:
    description: Changes player visibility
    usage: /<command>
  togglelogs:
    description: Enables command logging for admins
    usage: /<command>
  v:
    description: Shortcut for vanish
    usage: /<command>
  fly:
    description: Enables/disables flight.
    usage: /<command>
  report:
    description: Sends a message to online admins
    usage: /<command>
  god:
    description: Enables godmode
    usage: /<command>
  feed:
    description: Feeds to max hunger
    usage: /<command>
  heal:
    description: Heales to max hp
    usage: /<command>
  difficulty:
    description: Changes server difficulty
    usage: /<command>

## Gui commands:


