name: SausageSMP.main
version: 1.1.0.0
main: sausagesmp.corruptsausage.sausagesmp.main.SausageSMP.main
api-version: 1.16
authors: [ CorruptSausage ]
description: Base
## All commands:
commands:
  gms:
    description: Changes gamemode to survival
    usage: /<command>
  gmc:
    description: Changes gamemode to creative
    usage: /<command>
  day:
    description: Changes to daytime
    usage: /<command>
  night:
    description: Changes to nighttime
    usage: /<command>
  vanish:
    description: Changes player visibility
    usage: /<command>
  v:
    description: Shortcut for vanish
    usage: /<command>
  fly:
    description: Enables/disables flight.
    usage: /<command>
  easy:
    description: Changes difficulty to easy
    usage: /<command>
  normal:
    description: Changes difficulty to normal
    usage: /<command>
  hard:
    description: Changes difficulty to hard
    usage: /<command>
  peaceful:
    description: Changes difficulty to peaceful
    usage: /<command>
  report:
    description: Sends a message to online admins
    usage: /<command>
  god:
    description: Enables godmode
    usage: /<command>
  feed:
    description: Feeds to max hunger
    usage: /<command>
  heal:
    description: Heales to max hp
    usage: /<command>

## Gui commands:
  worldmenu:
    description: Opens world options/
    usage: /<command>

